version: "3.9"

services:
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env
    command: python3 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
